# Generated by Django 4.2 on 2023-04-17 15:43

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="utuberacc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("photo", models.ImageField(upload_to="media/utuber/%Y/%m/")),
                ("video_url", models.CharField(max_length=100)),
                ("description", ckeditor.fields.RichTextField()),
                ("city", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "crew",
                    models.CharField(
                        choices=[
                            ("solo", "solo"),
                            ("small", "small"),
                            ("large", "large"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "cameratype",
                    models.CharField(
                        choices=[
                            ("canon", "canon"),
                            ("nikon", "nikon"),
                            ("sony", "sony"),
                        ],
                        max_length=100,
                    ),
                ),
                ("subscribercount", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("entertainment", "entertainment"),
                            ("technology", "technology"),
                            ("lifestyle", "lifestyle"),
                            ("education", "education"),
                            ("vlogs", "vlogs"),
                            ("others", "others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("isfeatured", models.BooleanField(default=False)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
