# Generated by Django 4.2 on 2023-04-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0003_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="utubelink",
            field=models.CharField(default="https://www.youtube.com/", max_length=250),
        ),
    ]
